{% set name = "configspace" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Use upstream archive tarball because the PyPI sdist omits test subdirectories.
  url: https://github.com/automl/ConfigSpace/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aaaa15b3862d554d2164964248a2d17582faa23867c343f206fa21ad1c376a9b
  patches:
    # Fix incorrect package metadata in the upstream v1.2.2 tag.
    - fix_version.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - more-itertools
    - numpy
    - pyparsing
    - scipy
    - typing_extensions

test:
  source_files:
    - test
  imports:
    - ConfigSpace
  requires:
    - pip
    - pytest >=7
  commands:
    - pip check
    # Ignore test_functional.py because of ModuleNotFoundError: No module named 'pytest_cases',
    # pytest_cases isn't available on the main channel
    - pytest -v test --ignore="test/test_functional.py"

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  description: A simple python module to manage configuration spaces for algorithm configuration and hyperparameter optimization tasks.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/automl/ConfigSpace
  doc_url: https://automl.github.io/ConfigSpace/

extra:
  recipe-maintainers:
    - hadim
