{% set name = "ConfigSpace" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use upstream archive tarball for tests -- pypi does not include
  # the subdirs of test/
  url: https://github.com/automl/ConfigSpace/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7b2d129ce6d839d2bc75e77f6656915a633931a98dfb3c0117f4145ae5dda422

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - more-itertools
    - numpy
    - pyparsing
    - scipy
    - typing_extensions

test:
  source_files:
    - test
  imports:
    - ConfigSpace
  requires:
    - pip
    - pytest >=7
  commands:
    - pip check
    # Ignore test_functional.py because of ModuleNotFoundError: No module named 'pytest_cases',
    # pytest_cases isn't available on the main channel
    - pytest -v test --ignore="test/test_functional.py"

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  description: A simple python module to manage configuration spaces for algorithm configuration and hyperparameter optimization tasks.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/automl/ConfigSpace
  doc_url: https://automl.github.io/ConfigSpace/

extra:
  recipe-maintainers:
    - hadim
  skip-lints:
    - python_build_tool_in_run
