{% set name = "ConfigSpace" %}
{% set version = "0.4.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use upstream archive tarball for tests -- pypi does not include
  # the subdirs of test/
  url: https://github.com/automl/ConfigSpace/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 227426b9bd48d9379d6104ab58f3b60edd586b8bee003ddb3ee2a59fcdfd0459

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    # cython<3 would be valid for this release of ConfigSpace and
    # prevents various cast problems in the tests
    - cython <3
    - numpy {{ numpy }}
    - pip
    - setuptools
    - wheel
    - python
  run:
    # keep runtime use of cython compatible for the reasons above
    - cython <3
    - pyparsing
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  source_files:
    - test
  imports:
    - ConfigSpace
    - ConfigSpace.nx
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v test

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  description: A simple python module to manage configuration spaces for algorithm configuration and hyperparameter optimization tasks.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/automl/ConfigSpace
  doc_url: https://automl.github.io/ConfigSpace/

extra:
  recipe-maintainers:
    - hadim
  skip-lints:
    - python_build_tool_in_run
    - cython_must_be_in_host
