{% set name = "ConfigSpace" %}
{% set version = "0.4.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ConfigSpace-{{ version }}.tar.gz
  sha256: f7d35c0d7155e1e757c8a3797750098cc12ab77e447c38c8da07e74b6adb11f3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - setuptools
    - wheel
    - python
  run:
    - cython
    - pyparsing
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ConfigSpace
    - ConfigSpace.nx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/automl/ConfigSpace
  doc_url: https://automl.github.io/ConfigSpace/master/

extra:
  recipe-maintainers:
    - hadim
