{% set name = "ConfigSpace" %}
{% set version = "0.4.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ConfigSpace-{{ version }}.tar.gz
  sha256: 09c5ee343f2850865609cc91f2ab27da0a6182f7f196354f9550f6da578ea827

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - setuptools
    - wheel
    - python
  run:
    - cython
    - pyparsing
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - ConfigSpace
    - ConfigSpace.nx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/ConfigSpace
  summary: Creation and manipulation of parameter configuration spaces for automated algorithm configuration and hyperparameter tuning.
  description: A simple python module to manage configuration spaces for algorithm configuration and hyperparameter optimization tasks.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/automl/ConfigSpace
  doc_url: https://automl.github.io/ConfigSpace/master/

extra:
  recipe-maintainers:
    - hadim
  skip-lints:
    - python_build_tool_in_run
    - cython_must_be_in_host
